### ISSUE TITLE
Using the output

### ISSUE THREAD

**Issue by sunnefa** [Gibe/Umbraco-Link-Picker#1]
Hi, thanks for a useful package! Maybe I'm just dense but how do I then use the output from the link picker? I know it's in Json format, is there an object that I can deserialize it to or would I need to create that object myself?
Right now if I just deserialize to object I only get "object does not have a definition for url" errors.
Thanks for any help :-)

**Comment by karltynan** [comment]
The data that is returned (I will add to the readme) will be "id", "name", "url" and "target".

For dynamic I think you can just use <code>@CurrentPage.fieldName.url</code>. If you are using strongly typed, or want to deserialize the object, then I suggest using Newtonsoft.Json:

<pre>
var data = JsonConvert.DeserializeObject<LinkPickerModel>(value.ToString());

public class LinkPickerModel
{
	public int Id { get; set; }
	public string Name { get; set; }
	public string Url { get; set; }
	public string Target { get; set; }
}
</pre>

**Comment by sunnefa** [comment]
Thank you! I ended up creating a model class for this. Perhaps it would be a good idea to include that in the next version (if there is another version planned) or add something on the subject to the readme file :-)

**Comment by karltynan** [comment]
We are planning to release the converter we have created for this to use with Ditto by Lee Kelleher (https://github.com/leekelleher/umbraco-ditto) and bundle a model class for those not using Ditto.
