### ISSUE TITLE
New edit link functionality immediately updates link - rather than when Select is clicked in panel

### ISSUE THREAD

**Issue by joshua-stewart** [Gibe/Umbraco-Link-Picker#10]
The new ability to edit links is awesome, but there is one issue that will make it troublesome to use. When you edit a link and select a new link it appears the $scope value is immediately updated rather than when you click on the select button. This also removes the ability to click cancel and leave the link unchanged.

**Comment by zell71** [comment]
hey josh, i'll start work on this at some stage this week.

**Comment by joshua-stewart** [comment]
Thanks a bunch.

**Comment by zell71** [comment]
fixed - will create a pull request

**Comment by joshua-stewart** [comment]
Awesome! Thank you so much.

**Comment by karltynan** [comment]
This has now been updated with the latest release v1.3 - thanks @zell71
