### ISSUE TITLE
Missing icon for selected tree node

### ISSUE THREAD

**Issue by bjarnef** [Gibe/Umbraco-Link-Picker#12]
It seems for both v. 1.1 and v.1.2 that you rely on font-awesome for the selected icon in the tree.

![image](https://cloud.githubusercontent.com/assets/2919859/13489687/b79005a8-e128-11e5-8b36-09551a3fd793.png)

Inspecting the DOM it use

```
<i class="icon umb-tree-icon sprTree icon-fa-file-text-o" ng-click="select(node, $event)" title="#"></i>
```

Why not using the class `icon-check`?

![image](https://cloud.githubusercontent.com/assets/2919859/13489884/bdba7fd4-e129-11e5-9c86-38a773560414.png)

**Comment by karltynan** [comment]
Not sure where this refers to? Do you mean to keep the item checked if you want to edit it?

**Comment by bjarnef** [comment]
It is the missing font icon for checkmark that is missing (the blue checkmark). But I installed Link Picker on a clean install, so the issue is not in your package.

I the Umbraco install we also have "Font Awesome Icon Pack and Media Icons" package installed, which I think affect the tree icon:

https://our.umbraco.org/projects/backoffice-extensions/font-awesome-icon-pack-and-media-icons/bug-reports/75812-seems-to-affect-checkmark-for-tree-nodes
