### ISSUE TITLE
Link to media?

### ISSUE THREAD

**Issue by mrflo** [Gibe/Umbraco-Link-Picker#16]
Hi,

Thanks for sharing this! 

I would love to see it with an option to link to a media items as well that would be then the perfect link Picker.

**Comment by karltynan** [comment]
You can choose "Link to file" in the bottom-right of the the link picker dialog. This will allow you to choose or upload a new media item.

**Comment by mrflo** [comment]
Hi Karltynan,

Thanks it's working well!  Even in the grid.

Cheers

**Comment by karltynan** [comment]
Brilliant!
