### ISSUE TITLE
Add "+" icon before choose

### ISSUE THREAD

**Issue by bjarnef** [Gibe/Umbraco-Link-Picker#17]
I think you should add "+" icon before "choose" text, which make it more consistent with the core content picker.

Content Picker
![image](https://cloud.githubusercontent.com/assets/2919859/20592628/e7409f24-b22e-11e6-97e6-77eb035f6cab.png)

Link Picker
![image](https://cloud.githubusercontent.com/assets/2919859/20592641/f55dab6a-b22e-11e6-8f99-30f82865ecd3.png)

**Comment by karltynan** [comment]
It looks like the content picker in core is changing, so will look at changing the look/feel in the future: https://www.youtube.com/watch?v=2vqLaoCuil8&feature=youtu.be

Ideally, I would like to show the icon of the node when chosen (as per content picker), or a link for external items.
