### ISSUE TITLE
uDialogService.closeAll stops package working with Doc Type Grid Editor

### ISSUE THREAD

**Issue by number45** [Gibe/Umbraco-Link-Picker#2]
I have been trying to use this package with the new Doc Type Grid Editor package and have found that it doesn't work.  When you select or enter a link and click the Select button both the link picker and DTGE dialogs are closed.

A fix may be to replace closeAll with just close.

**Comment by karltynan** [comment]
This how now been updated with version 1.1 - thanks for noticing and helping! #h5yr
