### ISSUE TITLE
LinkPicker for multiple links

### ISSUE THREAD

**Issue by blachawk** [Gibe/Umbraco-Link-Picker#20]
Am I missing something or is there no way to reference multiple links per content item with Link Picker?  If I place the following on a template, it only reveals one link...

```
@* return an external URL *@
<p><a href="@CurrentPage.linkpicker.url">@CurrentPage.linkpicker.url</a></p>
```

Is there documentation on how to add as many links as one editor wants with Link Picker? rather than hard-coding multiple links per template?

**Comment by stevetemple** [comment]
It's designed for picking a single link, you can put into either Archetype or Nested Content for multiple

**Comment by blachawk** [comment]
ahh, that makes sense and thanks for the additional tips!
