### ISSUE TITLE
Update picker to Umbraco 7.6+ style

### ISSUE THREAD

**Issue by bjarnef** [Gibe/Umbraco-Link-Picker#24]
You might want to update the style to be consistent with Umbraco 7.6+

You could either have a look at the core link picker
https://github.com/umbraco/Umbraco-CMS/blob/e0025db56d52b770d2b3aedbd48a3b804fd15ef0/src/Umbraco.Web.UI.Client/src/views/common/dialogs/linkpicker.html

https://github.com/umbraco/Umbraco-CMS/blob/e0025db56d52b770d2b3aedbd48a3b804fd15ef0/src/Umbraco.Web.UI.Client/src/views/common/dialogs/linkpicker.controller.js

or have a look at the `umb-node-preview` (Added in Umbraco 7.6)
https://github.com/umbraco/Umbraco-CMS/blob/e0025db56d52b770d2b3aedbd48a3b804fd15ef0/src/Umbraco.Web.UI.Client/src/common/directives/components/umbnodepreview.directive.js

Otherwise an easy fix could be to add e.g. the class `umb-node-preview-add` to "choose link".

![image](https://user-images.githubusercontent.com/2919859/32231066-ea52b192-be54-11e7-8b50-015943722a2b.png)

![image](https://user-images.githubusercontent.com/2919859/32231078-f662ddf4-be54-11e7-9606-24b0093b29d4.png)

**Comment by stevetemple** [comment]
Hi, v1.5.0 now matches the styling of 7.6+

Thanks
