### ISSUE TITLE
Link not updating when domain for site is updated?

### ISSUE THREAD

**Issue by nielyng** [Gibe/Umbraco-Link-Picker#28]
Hi! 

I have an issue that I need a bit help with. My client has a huge site and has used the picker all over the site. However, the site used to have multiple domains, but in relation to SEO they have set up redirects from one domain to the other and removed one domain from the site. However, even after republish, all Gibe Linkpickers contain the OLD domain in the link. 

Is this in any way fixable? 

The client is using Umbraco 7.4.3 and the latest Gibe Link Picker from the repository with our own model (since this was not included in the package)

**Comment by karltynan** [comment]
If you are using internal content that you should be getting the URL based on the node ID. 

Unfortunately, much like a WYSIWYG and other tools, external links or hand-coded internal links cannot be retrieved this way.

If this is the case, you could try finding references of URLs in the database and make them relative URLs. Or you could update the domain?

Finally, do you not have any 301 redirects setup to forward users who have bookmarked or used the link other websites?

**Comment by louisjrdev** [comment]
@nielyng I believe this has been fixed as part of #35 and this issue can now be closed?
