### ISSUE TITLE
Dlls missing from install package

### ISSUE THREAD

**Issue by jattwood** [Gibe/Umbraco-Link-Picker#30]
I was having the hardest time trying to use strongly typed access to the property editor until I realized just now that your package manifest is missing the dlls. Looks like this goes right back to the beginning. Is this intentional?

Cheers,

Jamie

**Comment by amrosama2020** [comment]
please check my comment https://github.com/Gibe/Umbraco-Link-Picker/issues/29#issuecomment-417098385

**Comment by stevetemple** [comment]
DLLs are in v 1.4.x and above so should not be an issue any more
