### ISSUE TITLE
Link Picker problem

### ISSUE THREAD

**Issue by Budolfsen** [Gibe/Umbraco-Link-Picker#4]
Hi - newbie to the Umbraco scene - so please bare with the stupid questions:)

I have installed this plugin - which do the job excellent, but now I want to use this inside of a node treee picker - so my author can choose links and give them a name - and these links will show up in a sidebar - see code below

@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

    @foreach (var sideBar in CurrentPage.sidebar.Split(','))
    {
		var item = Umbraco.Content(sideBar);

		<section class="sideBar">
            <header class="sideBar__header">
                <h1 class="sideBar__headerTitle mainTitle">@item.Title</h1>
            </header>
            <div class="sideBar__content">
               @item.Body
            </div>
					<div class="link">
						<a href="@CurrentPage.link.url" class="button button__default">pageLink.name</a>
					</div>
        </section>
	}

If I use the @CurrentPage.link.url I get an error telling me that the url is not defined in string - and if I use th @item.Url - I get the link to the page.

Hope you can help me with this question....?

**Comment by karltynan** [comment]
I am not sure what you mean exactly...

If you want the URL of the link in the sidebar item, surely it would be "item.url", as "CurrentPage.link.url" will be checking for a link property on the current doctype, not within the sidebar item?

So if you have a Link Picker property called "link" in each sidebar item, it would be "item.link.url"?

**Comment by karltynan** [comment]
Maybe try something like this...

<pre>
@foreach(var sideBar in CurrentPage.sidebar.Split(','.ToCharArray()))
{
  var item = Umbraco.Content(sideBar);
  &lt;a href="@item.link.url" target="@item.link.target"&gt;@item.link.name&lt;/a&gt;
}
</pre>

**Comment by karltynan** [comment]
No response, closed issue.
