### ISSUE TITLE
Is it possible to edit a Link Picker?

### ISSUE THREAD

**Issue by Smitche** [Gibe/Umbraco-Link-Picker#5]
Is it possible to edit a Link, without deleting old settings?

![link-picker](https://cloud.githubusercontent.com/assets/5181160/10099671/2ceb7014-638c-11e5-9300-6edc1ae26757.png)

**Comment by karltynan** [comment]
Not currently. It's using the built-in link picker dialog in Umbraco, and clicking an existing link should take the user to the URL. Maybe edit functionality could be a useful future improvement, but only if the link picker dialog has the ability to pass in defaults.

**Comment by karltynan** [comment]
Feature request. closed issue.
